### ISSUE TITLE
Install iptsd mx linux not working Surface Pro 4

### ISSUE THREAD

**Issue by kwai-chang** [linux-surface/iptsd#103]
I was working with debian 11, everything (without camera) was working fine.
Now I wanted to give mx linux a chance, because it is fine installation package on board.

I could not get touchpad working. No errors while installing or enabling, just not working.

**Comment by kwai-chang** [comment]
output of systemctl status iptsd:

System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Der Rechner ist nicht aktiv

**Comment by StollD** [comment]
iptsd only includes a systemd service file, so only distributions that use systemd for service management are supported. I only know systemd, so support for different service managers would have to come from people that have experience with them.

I vaguely remember that MX allows you to boot with systemd as PID 1 in the bootloader, so you should try that.

**Comment by kwai-chang** [comment]
How to? "systemctl enable iptsd" works with no error but not working also while restart, also displayed as succesfully installed

![image](https://user-images.githubusercontent.com/48348824/210442416-d25a91be-4c07-4f70-8897-bfb4abf68cc8.png)
![image](https://user-images.githubusercontent.com/48348824/210442555-1a75bc63-3c62-470f-be33-d0411ef1c4cd.png)

**Comment by NP-chaonay** [comment]
@kwai-chang 

1) iptsd has notthing to do with touchpad, but touch screeen and pen
2) systemd installed and loaded is not enough,  it is required to be loaded in PID 1, PID 1 means the init program of kernel,
that init program must be systemd not something else, and it is abnormal on systemd-as-init-program system that gives `System has not been booted with systemd as init system (PID 1). Can't operate.`.

**Comment by kwai-chang** [comment]
thanks for comment, just misspelling. Meaning was touch screen and pen.

**Comment by kwai-chang** [comment]
Do not know how to setup init system (PID1). With Kernel 6.0.13 next error in rtl3883. Thunderbird still on ver 78.
So I will go back to debian 11.06.
I like the structure and implementad packages in MX Linux but main functions not supported

**Comment by kwai-chang** [comment]
https://daylifetips.com/enable-systemd-on-mx-linux/
