### ISSUE TITLE
Can't find hidraw device ID or run iptsd with the device path

### ISSUE THREAD

**Issue by MAFINZ** [linux-surface/iptsd#109]
I installed the latest version of iptsd on my computer by going to the latest version release then downloading the .deb file. After that I installed it by ``` cd Downloads/ ``` then ```sudo apt install ./iptsd-file.deb ``` (Im using iptsd-file.deb because I have no clue what the name is). After it installed I ran ``` sudo ./etc/iptsd-find-hidraw ``` and it gave me the error ```sudo: ./etc/iptsd-find-hidraw: command not found``` . I am stuck here and can't find how to fix it.

**Comment by StollD** [comment]
If you install iptsd from a package it is just `sudo iptsd-find-hidraw`. The command from the README you used is for building iptsd from source.

If you install iptsd from a package, you also dont need to run it manually. You can just reboot and udev should launch it automatically with the correct device name.

**Comment by MAFINZ** [comment]
Ah ok thanks!
