### ISSUE TITLE
Surface Book 3: fails to start

### ISSUE THREAD

**Issue by xanf** [linux-surface/iptsd#12]
```
[root@discovery iptsd]# ./iptsd 
Connected to device 045e:09b1
Display size is 0
main.(*IptsDevices).Create
	/root/iptsd/devices.go:166
main.main
	/root/iptsd/main.go:47
runtime.main
	/usr/lib/go/src/runtime/proc.go:203
runtime.goexit
	/usr/lib/go/src/runtime/asm_amd64.s:1373
```

Anything I'm missing?
Kernel is stock arch kernel + patch from `intel-precise-touch` + module  built from `feature/uapi` branch

**Comment by xanf** [comment]
Ah, nvm
VID:PID `045e:09b1` pair was missing from config

**Comment by StollD** [comment]
I added the missing device ID a while ago, so this issue should be resolved.
