### ISSUE TITLE
Calibration

### ISSUE THREAD

**Issue by lviggiani** [linux-surface/iptsd#126]
According to [this](https://github.com/linux-surface/linux-surface/issues/96#issuecomment-1514940494) announcement I have upgraded iptsd to 1.2.0.
The announcement also says to delete old calibration ad do it again. I'm trying to do it from gnome control panel, but when the first marker appear on the screen and I try to click them with the pen, nothing happens. Can you help me please with calibration?

**Comment by lviggiani** [comment]
Also I have noticed that pen latency has increased and the pointer freezes for a while every couple of seconds while continuously moving the pen on the screen. Does it have to do with calibration?

**Comment by StollD** [comment]
That sentence is about the calibration data for iptsd's palm detection: https://github.com/linux-surface/iptsd/wiki/Calibrating-iptsd

Pen calibration is currently not possible (iptsd doesn't have the functionality, and the GNOME built-in one is broken).

**Comment by lviggiani** [comment]
Thanks!
