### ISSUE TITLE
[arch linux]I have installed the iptsd,but can`t find this services

### ISSUE THREAD

**Issue by qwqpap** [linux-surface/iptsd#138]
I installed the iptsd and the other kernel [as this guild ](https://github.com/linux-surface/linux-surface/wiki/Installation-and-Setup)
but i can\`t start this service althought i had reboot
`sudo systemctl enable iptsd                             
Failed to enable unit: Unit file iptsd.service does not exist.
`
i trust i made some stupid mistake:/
i didn`t find it there
` user ls
app.slice                               plasma-kglobalaccel.service
at-spi-dbus-bus.service                 plasma-krunner.service
background.slice                        plasma-kscreen-osd.service
basic.target                            plasma-kscreen.service
bluetooth.target                        plasma-ksmserver.service
dbus-org.bluez.obex.service             plasma-ksplash-ready.service
dbus.service                            plasma-ksplash.service
dbus.socket                             plasma-ksystemstats.service
dconf.service                           plasma-kwallet-pam.service
deepin-turbo-booster-desktop.service    plasma-kwin_wayland.service
deepin-turbo-booster-dtkwidget.service  plasma-kwin_x11.service
default.target                          plasma-plasmashell.service
dirmngr.service                         plasma-polkit-agent.service
dirmngr.socket                          plasma-powerdevil.service
drkonqi-coredump-cleanup.service        plasma-restoresession.service
drkonqi-coredump-cleanup.timer          plasma-workspace-wayland.target
drkonqi-coredump-launcher.socket        plasma-workspace-x11.target
drkonqi-coredump-launcher@.service      plasma-workspace.target
exit.target                             plasma-xdg-desktop-portal-kde.service
filter-chain.service                    plasma-xembedsniproxy.service
gcr-ssh-agent.service                   printer.target
gcr-ssh-agent.socket                    pulseaudio-x11.service
glib-pacrunner.service                  pulseaudio.service
gnome-keyring-daemon.service            pulseaudio.socket
gnome-keyring-daemon.socket             session.slice
gpg-agent-browser.socket                shutdown.target
gpg-agent-extra.socket                  smartcard.target
gpg-agent-ssh.socket                    sockets.target
gpg-agent.service                       sockets.target.wants
gpg-agent.socket                        sound.target
graphical-session-pre.target            systemd-exit.service
graphical-session.target                systemd-tmpfiles-clean.service
kde-baloo.service                       systemd-tmpfiles-clean.timer
kio-fuse.service                        systemd-tmpfiles-setup.service
obex.service                            timers.target
p11-kit-server.service                  tracker-xdg-portal-3.service
p11-kit-server.socket                   waybar.service
paths.target                            wireplumber.service
pipewire.service                        wireplumber@.service
pipewire.socket                         xdg-desktop-autostart.target
plasma-baloorunner.service              xdg-desktop-portal-gnome.service
plasma-core.target                      xdg-desktop-portal-gtk.service
plasma-dolphin.service                  xdg-desktop-portal-rewrite-launchers.service
plasma-gmenudbusmenuproxy.service       xdg-desktop-portal.service
plasma-kactivitymanagerd.service        xdg-document-portal.service
plasma-kcminit-phase1.service           xdg-permission-store.service
plasma-kcminit.service                  xdg-user-dirs-update.service
plasma-kded.service
`

**Comment by StollD** [comment]
You only have to install the package, iptsd is started automatically by udev which is why the guide does not mention starting or enabling it.

The service itself is called `iptsd@dev-hidrawX.service`, where X is the number of the touchscreens HID device on your machine. If you want to find the current service name, you can use `iptsd-find-service`, like this: `systemctl status $(iptsd-find-service)`.

**Comment by qwqpap** [comment]
thanks ,i had sovled this, i forget to change the uefi setting after that sorry
