### ISSUE TITLE
Arch dependency error libspdlog.so

### ISSUE THREAD

**Issue by Emporea** [linux-surface/iptsd#140]
When trying to update the system where i installed linux kernel and iptsd i get this error:

```
error: failed to prepare transaction (could not satisfy dependencies)
:: installing spdlog (1.12.0-1) breaks dependency 'libspdlog.so=1.11-64' required by iptsd
```

please have a look.
If you need more information just ask.

**Comment by StollD** [comment]
I am currently working on statically linking all the dependencies on Arch, so this should be solved soon and not happen again.

**Comment by addz** [comment]
+, dependencies on Arch.
Thank you @StollD for a fast response and being on top of it!

iptsd is so awesome btw. Arch + Surface + pen, is an unparalleled experience :exploding_head:.  Thanks for all of your hard work!!

(Also thanks @Emporea for opening the ticket :smile:)

**Comment by StollD** [comment]
I tagged a new release, should take a while to go down the pipeline and into the repo but I hope that fixes the issue.

The package now builds the dependencies inline wherever possible, this means it has no dependencies other than libc / libstdc++, and the X11 / OpenGL libraries for the iptsd-show tool. But I dont think those will break their ABI anytime soon.

> iptsd is so awesome btw. Arch + Surface + pen, is an unparalleled experience

Eh, it could be much better, but a lot of that is due to hardware limits (latency). But thank you. :)

**Comment by sughero** [comment]
Thank you. I had same problem so as soon as you changed the package I grabbed  and installed it.
Since pacman is synced with the repo https://pkg.surfacelinux.com/arch/ I get the following mismatch:

 `-> iptsd: local (1.3.2-1) is newer than linux-surface  (1.3.1-1)`

**Comment by addz** [comment]
Thanks! Verified issue is resolved. I haven't seen the updated package in the main repo yet, but installed `1.3.2` build manually and installs/works fine. Thanks!


For any other Arch users that stumble across this and aren't sure:

1. Go to [https://github.com/linux-surface/iptsd/actions](https://github.com/linux-surface/iptsd/actions). Select whatever is newest with the fix.
2. Download the pkg from the Artifacts section
3. Manually install via `pacman -U <pkg>` (after unzipping).
4. Profit from touch and pen goodness.
