### ISSUE TITLE
 Surface Pencil interchanged x and y coordinates in portrait mode Ubuntu 22.04 Wayland

### ISSUE THREAD

**Issue by pepilyser** [linux-surface/iptsd#141]
Hello,
So I have the exact same issue as "Surface Pencil not usable in portrait mode due interchanged x and y coordinates #139 " and I also reinstalled Ubuntu 22.04 as a whole and it did work for some time, but, all of a sudden the coordinates changed from nowhere and no particular reason.
I was literally using the pen properly and in an instant it interchanged x and y coordinates again in portrait mode.

I don't want to reinstall Ubuntu again and again as it happened today and I reinstalled Ubuntu yesterday.

The issue probably comes from Wayland since it works perfectly on the login screen.

If I open this issue it's more about for investigating where this issue comes from exactly and find a fix that doesn't ask to reinstall Ubuntu every time if it happens that often or if there is a way to manually change the coordinates for the surface pen.

**Comment by StollD** [comment]
This is an Ubuntu / GNOME issue, please report it to them because they are the only ones who can fix it.
