### ISSUE TITLE
How do I disable touch input when pen input is enabled?

### ISSUE THREAD

**Issue by IlyaKonFetka** [linux-surface/iptsd#145]
Is there any way to temporarily disable/enable touch input when using a pen in laptops with touch screens? Of course, I know that in Windows settings it is possible to disable touch input when using a pen. In this case, while drawing with a pen, I can touch the screen with my hand. However, this does not make drawing much easier. I want the hand not to be recognized at all for a while, so that I can put my hand to the screen first, then start using the pen. At the same time (if possible) be able to quickly regain control of the hand to scale the canvas. How can this be implemented?
I use ASUS Vivobook s 16 flip with Win 10.

**Comment by StollD** [comment]
> I use ASUS Vivobook s 16 flip with Win 10.

I am confused. Windows doesnt use or need iptsd, it is only needed for enabling the touchscreen of MS Surface devices on Linux based operating systems.

Or am I misunderstanding you somehow?

**Comment by IlyaKonFetka** [comment]
> > I use ASUS Vivobook s 16 flip with Win 10.
> 
> I am confused. Windows doesnt use or need iptsd, it is only needed for enabling the touchscreen of MS Surface devices on Linux based operating systems.
> 
> Or am I misunderstanding you somehow?
I know what iptsd is for. I just want my laptop on Win10 to not recognize hand touches, but only pen touches when I want it.

**Comment by IlyaKonFetka** [comment]
> > I use ASUS Vivobook s 16 flip with Win 10.
> 
> I am confused. Windows doesnt use or need iptsd, it is only needed for enabling the touchscreen of MS Surface devices on Linux based operating systems.
> 
> Or am I misunderstanding you somehow?

I know what iptsd is for. I just want my laptop on Win10 to not recognize hand touches, but only pen touches when I want it.
