### ISSUE TITLE
Surface Pro 7 Touch not working since last update

### ISSUE THREAD

**Issue by DerHumm3l** [linux-surface/iptsd#148]
Hi

im using pop os on my surface pro 7. I didn't really used my surface this month, but updated all packages yesterday. Today I realized that my touchscreen isn't working anymore. I checked the iptsd service with `systemctl status $(iptsd-find-service)` which printed the following:

```
 iptsd@-.service - Intel Precise Touch & Stylus Daemon
     Loaded: loaded (/lib/systemd/system/iptsd@.service; static)
     Active: inactive (dead)
       Docs: https://github.com/linux-surface/iptsd
```

which seems to be issue that the touchscreen isn't working, I think. I also checked the `libwacom-list-local-devices` ouput, which gives me:

```
Failed to find any devices known to libwacom.
```

which isn't good, I think. Can someone guide me how I can fix the touchscreen?

**Comment by StollD** [comment]
Please post your dmesg, and make sure that you haven't accidentally booted into a stock kernel (check if `uname -r` contains surface).

**Comment by DerHumm3l** [comment]
Kernel was indeed wrong. I switched the kernel with `sudo kernelstub -v -k <vmlinuz_path> -i <initrd.img_path>`. The appropriate vmlinuz and initrd.img files for the surface kernel were in my boot directory. After restart everything works fine.

Any idea why the default it switched the default kernel after updating all packages? Is it because of an update to the surface kernel or perhaps a pop os specific thing, which caused it?
