### ISSUE TITLE
Surface 5 Pro Hardware Buttons

### ISSUE THREAD

**Issue by Djrush86** [linux-surface/iptsd#157]
I have installed all current versions of Bliss Os 14,15 and 16 with Linux Surface Patches on my Surface 5 Pro whit Windows but at no Version, my buttons for Power an Loudness and Silence are working. That's the only thing what doesn't work. Is it a problem whit the current iptsd?

**Comment by StollD** [comment]
No, because iptsd doesn't drive the power and volume buttons.
