### ISSUE TITLE
[SB3] Touchscreen non functional

### ISSUE THREAD

**Issue by AbramMaldonado** [linux-surface/iptsd#160]
I installed the latest version of Ubuntu and the [linux-surface](https://github.com/linux-surface/linux-surface) but have not been able to get the touch screen working
I am relatively new to Ubuntu and would like some direction or assistance
I have tried reinstalling just about everything from the kernel, Ubuntu, iptsd and i have little idea what else should i do to get the touchscreen working

sudo systemctl start $(iptsd-find-service)
`#nothing`
sudo systemctl status $(iptsd-find-service)
```
○ iptsd@-.service - Intel Precise Touch & Stylus Daemon
     Loaded: loaded (/lib/systemd/system/iptsd@.service; static)
     Active: inactive (dead)
       Docs: https://github.com/linux-surface/iptsd

Mar 17 01:54:58 nyakun-Surface-Book-3 systemd[1]: Started Intel Precise Touch & Stylus Daemon.
Mar 17 01:54:58 nyakun-Surface-Book-3 systemd[1]: Stopping Intel Precise Touch & Stylus Daemon...
Mar 17 01:54:58 nyakun-Surface-Book-3 systemd[1]: iptsd@-.service: Deactivated successfully.
Mar 17 01:54:58 nyakun-Surface-Book-3 systemd[1]: Stopped Intel Precise Touch & Stylus Daemon.
```
sudo /usr/bin/iptsd
```
DEVICE is required
Run with --help for more information.
```

Below is the output of sudo dmesg
[output.txt](https://github.com/linux-surface/iptsd/files/14626494/output.txt)

**Comment by mercifulboss** [comment]
I have exactly the same issue as you on Garuda gnome. Why did you close it? 

I don't understand why IPTSD is not working (and with it the touch screen)
