### ISSUE TITLE
unit fails on suspend

### ISSUE THREAD

**Issue by Flameopathic** [linux-surface/iptsd#162]
### expected behavior
iptsd does nothing while system is suspended and returns to functionality when unsuspending

### actual behavior
suspend system
unit reports `[warning] Input/output error` repeatedly
reaches 50 reports, automatically exits process and reports `[error] No such device`
can start the unit again, functions fully until next suspend

### system
NixOS w/ flakes, Surface Pro 7, using configuration from [nixos-hardware](https://github.com/NixOS/nixos-hardware/tree/master/microsoft/surface). nothing custom in `iptsd.conf`.

**Comment by StollD** [comment]
nixos-hardware patches iptsd to use a broken and unsupported service file, so this is how they choose to present it to you.

You need to report this to them as they are the only ones who are able to fix it.

**Comment by Flameopathic** [comment]
gotchya - will take it up with them. thank you for the quick response!
