### ISSUE TITLE
No Go files when building

### ISSUE THREAD

**Issue by TimmyOl** [linux-surface/iptsd#19]
I cant build it, it just says no Go files in ipts folder.
I have Go 1.14 installed
im on Pop OS 20.10 on a surface book 2 13" and have linux-surface kernel 5.9.1 and only single touch if its even that, just marking everything when i touch the screen with or without the pen.

I dont know what more information to give?

**Comment by StollD** [comment]
We switched iptsd to C, but the readme hasnt been updated yet. So no more go code that you can compile.

If you want to build iptsd yourself, you need to use meson now:
```bash
$ meson build
$ ninja -C build
$ sudo ./build/iptsd
```

> im on Pop OS 20.10 on a surface book 2 13" and have linux-surface kernel 5.9.1 and only single touch if its even that, just marking everything when i touch the screen with or without the pen.

For a good touch experience you need to use Wayland. X11, which Ubuntu and derivates default to, has no support for touchscreens or styli, and has to emulate a mouse pointer. So touching means left-click, and moving means scrolling.

**Comment by TimmyOl** [comment]
> We switched iptsd to C, but the readme hasnt been updated yet. So no more go code that you can compile.
> 
> If you want to build iptsd yourself, you need to use meson now:
> 
> ```shell
> $ meson build
> $ ninja -C build
> $ sudo ./build/iptsd
> ```
> 
> > im on Pop OS 20.10 on a surface book 2 13" and have linux-surface kernel 5.9.1 and only single touch if its even that, just marking everything when i touch the screen with or without the pen.
> 
> For a good touch experience you need to use Wayland. X11, which Ubuntu and derivates default to, has no support for touchscreens or styli, and has to emulate a mouse pointer. So touching means left-click, and moving means scrolling.

That worked, thanks :D 
Still only singe touch though even though im using wayland :(
