### ISSUE TITLE
Surface Laptop 3 invalid product ID?

### ISSUE THREAD

**Issue by Tim024** [linux-surface/iptsd#33]
Iptsd is not working out-of-the-box on my surface laptop-3
```
> sudo iptsd

Connected to device 045E:0984
ERROR: ../src/devices.c:286: Display size is 0!
: Invalid argument
ERROR: ../src/main.c:106: Failed to create uinput devices: Invalid argument
```

However, when I replace the device ID in /usr/share/ipts/surface-laptop3-13.conf (045E:0983) with the device ID thrown by the error (045E:0984), it works like a charm. Is it a typo or a different device?

**Comment by StollD** [comment]
It is probably a different device. I will add a file for the second device ID. In the meantime, if you dont want to edit the file under `/usr` you can also copy it to `/etc/ipts.conf`. That file has no check for the device ID and will always get loaded.

Didnt Microsoft release an Intel version of the SL3 with a 15" display? Do you maybe have that one?

**Comment by Tim024** [comment]
Ah! Indeed after verification, I do have a 15" SL3 which explains the different ID.

Thanks for the tip of using ipts.conf, I will do that in the meantime. Thanks a lot!
