### ISSUE TITLE
iptsd on SP4 exits after few hours

### ISSUE THREAD

**Issue by afalout** [linux-surface/iptsd#35]
On my SP4: Touch works OK after reboot for few hours, then it stops working. When I check iptsd, it exited. I can manually start it, and it runs for few seconds, then exits again:

sudo systemctl start iptsd 
sudo systemctl status iptsd
● iptsd.service - Intel Precise Touch & Stylus Daemon
     Loaded: loaded (/lib/systemd/system/iptsd.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2021-02-19 18:23:40 NZDT; 1s ago
       Docs: https://github.com/linux-surface/iptsd
   Main PID: 25951 (iptsd)
      Tasks: 1 (limit: 9312)
     Memory: 228.0K
     CGroup: /system.slice/iptsd.service
             └─25951 /usr/bin/iptsd

Feb 19 18:23:40 SurfacePro4main systemd[1]: Started Intel Precise Touch & Stylus Daemon.

sudo systemctl status iptsd
● iptsd.service - Intel Precise Touch & Stylus Daemon
     Loaded: loaded (/lib/systemd/system/iptsd.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2021-02-19 18:23:45 NZDT; 17s ago
       Docs: https://github.com/linux-surface/iptsd
    Process: 25951 ExecStart=/usr/bin/iptsd (code=exited, status=237/KEYRING)
   Main PID: 25951 (code=exited, status=237/KEYRING)

Feb 19 18:23:40 SurfacePro4main systemd[1]: Started Intel Precise Touch & Stylus Daemon.
Feb 19 18:23:45 SurfacePro4main iptsd[25951]: ERROR: ../src/control.c:52: Failed to send feedback: No such device
Feb 19 18:23:45 SurfacePro4main iptsd[25951]: ERROR: ../src/control.c:75: Failed to flush buffers: No such device
Feb 19 18:23:45 SurfacePro4main iptsd[25951]: ERROR: ../src/main.c:83: Failed to start IPTS: No such device
Feb 19 18:23:45 SurfacePro4main systemd[1]: iptsd.service: Main process exited, code=exited, status=237/KEYRING
Feb 19 18:23:45 SurfacePro4main systemd[1]: iptsd.service: Failed with result 'exit-code'.

Same if I start it on command line:
sudo /usr/bin/iptsd
ERROR: ../src/control.c:52: Failed to send feedback: No such device
ERROR: ../src/control.c:75: Failed to flush buffers: No such device
ERROR: ../src/main.c:83: Failed to start IPTS: No such device

Any advice appreciated

**Comment by StollD** [comment]
Can you please post your dmesg?

**Comment by afalout** [comment]
I was not able to consistently reproduce this issue after I added more swap to the system. Looking at #379, it just may be that I was indeed Out of Memory. It also seems something is not right with suspend/resume cycle, but again, I was not able to consistently reproduce this one either.
Feel free to close for now, I will update and provide dmesg if I manage to reproduce this again.
Thanks

**Comment by StollD** [comment]
Your issues are not out of memory issues though. Well, at least I can't say so without seeing your dmesg.

But if it doesnt happen for you anymore, "IPTS was cursed" is a good explanation in my book. :P
