### ISSUE TITLE
SB1 performance

### ISSUE THREAD

**Issue by tmarkov** [linux-surface/iptsd#4]
I just tested iptsd on SB1, kernel 5.6.15 on Manjaro.

Pen works great. The lines are very smooth. When I draw lines very fast, the line lags a bit behind, but not by much.

Touch, however, works poorly. When I touch the screen and hold, the mouse starts jumping all over the part of the screen to the left and above where I'm touching. Also apps start zooming in and out.

**Comment by StollD** [comment]
Thanks for testing!

The issues with the touchscreen are unfortunate, but kinda expected at this stage I guess. The algorithm is very very simple: Just find the first 10 local maximas in the heightmap and calculate the exact screen position using their direct neighbors. There is no noise filtering or palm detection going on.

Your problem sounds like something I have observed on my SB2 a while ago: When you press on the screen, a different area gets suddenly filled with noise (depending on how hard you pressed on the display). I still have a similar issue from time to time with iptsd, but restarting the device usually fixes it for a while. Maybe that will work for you too?

The output of `sudo evtest` for the `IPTS Touch` device would be interesting too, although I don't think it will actually help with solving the problem.

**Comment by tmarkov** [comment]
That makes sense. I was experimenting before with the heatmap on SB1, and usually there is noise where I'm not pressing. It was pretty consistent for me though rather than sporadic.

Putting a threshold on the local maximas was doing the trick. I think I was using 0.5.

**Comment by tmarkov** [comment]
Increasing the threshold does fix the pointer jumping around issue. However, now I can see issue: when moving the finger around, the pointer lags a significant amount behind - sometimes by the whole screen width.

**Comment by StollD** [comment]
How did you increase the threshold? I tried simply replacing the average based threshold with a constant value (0.5 sounded like a good idea so I used that), and it seems to work fine for me.

```diff
diff --git a/processing/heatmap/contact.go b/processing/heatmap/contact.go
index 838fb17..8fe453a 100644
--- a/processing/heatmap/contact.go
+++ b/processing/heatmap/contact.go
@@ -1,7 +1,6 @@
 package heatmap
 
 func (hm Heatmap) Contacts(contacts []Contact) int {
-	threshold := hm.Average() + 1
 	c := 0
 
 	if len(contacts) == 0 {
@@ -10,7 +9,7 @@ func (hm Heatmap) Contacts(contacts []Contact) int {
 
 	for x := 0; x < hm.Width; x++ {
 		for y := 0; y < hm.Height; y++ {
-			if float32(hm.Value(x, y)) < threshold {
+			if hm.Value(x, y) < 127 {
 				continue
 			}

```

**Comment by tmarkov** [comment]
I kept it average-based, just replaced the 1 with 5:
```
 func (hm Heatmap) Contacts(contacts []Contact) int {
-       threshold := hm.Average() + 1
+       threshold := hm.Average() + 5
        c := 0
```

**Comment by tmarkov** [comment]
Ah, yea, I messed up. In addition to increasing the threshold, I had added some debug prints that were actually causing the lags. It works fine now.
