### ISSUE TITLE
Is this necessary if I'm already using linux-surface/linux-surface?

### ISSUE THREAD

**Issue by gamer191** [linux-surface/iptsd#41]
Is this necessary if I'm already using [linux-surface/linux-surface](https://github.com/linux-surface/linux-surface)?

**Comment by qzed** [comment]
`iptsd` is a user-space daemon, so it's not part of the kernel. Essentially, this daemon provides necessary parts for the touchscreen. So if you want touch support on gen 4 and later (e.g. Surface Pro 4, 5, ..., Surface Books, Surface Laptops) devices (with a non v4.19 kernel), you'll need this. This isn't required (i.e. does nothing) on the  Surface Go and pre-gen4 (Surface Pro 3, Surface 3, ...) devices, on those touch is supported out of the box.

If you have the package repository set up, you can simply install the `iptsd` package.

**Comment by gamer191** [comment]
Thank you very much @qzed
