### ISSUE TITLE
iptsd fails to start on Surface Pro 6

### ISSUE THREAD

**Issue by dread-pirate-johnny-spaceboots** [linux-surface/iptsd#48]
Running Gentoo w/ the linux-surface kernel, OpenRC & Xorg + i3. Built iptsd from source but when trying to run it:

`Connected to device 045E:001F
ERROR: ../src/devices.c:286: Display size is 0!
: Invalid argument
ERROR: ../src/main.c:106: Failed to create uinput devices: Invalid argument`

I have 16 files under /dev/ipts ranging from 0 - 15, all `crw-------  1  root  root  241,`

**Comment by dread-pirate-johnny-spaceboots** [comment]
Not sure why exactly but the build script was failing on a check for systemd (because I'm using elogind?), but removing that entire condition from the meson.build script allowed it to build.

I also tried installing from the linux-surface repo but that fails to emerge for me:

`ERROR: sys-firmware/iptsd-0.4::linux-surface failed (unpack phase):

unpack: /var/tmp/portage/sys-firmware/iptsd-0.4/distdir/master.zip does not exist
`

**Comment by ls-r** [comment]
Hello!

For the first problem, the daemon probably can't access the configuration files it needs. The configs (in [iptsd/config](https://github.com/linux-surface/iptsd/tree/master/config)) define the width and height of the screen for different Surface devices. The `ERROR: ../src/devices.c:286: Display size is 0!` line is printed if the display width or height is not defined.

If you've installed the daemon (to `/usr/bin/` or `/usr/local/bin/`, for example), then you need to also put the config files I mentioned above into the appropriate directory (likely `/usr/share/iptsd/` or `/usr/local/share/iptsd/`). This *should* be handled by running `sudo ninja -C build install` as in the README. 

If instead you're running the daemon prior to installing it, you have to be in the project's base directory for it to work. For example, this works:
```sh
$ pwd
/some/dir/iptsd
$ sudo ./build/iptsd
Connected to device 045E:001F
```

but this doesn't:
```sh
$ pwd
/some/dir/iptsd/build
$ sudo ./iptsd
Connected to device 045E:001F
ERROR: ../src/devices.c:286: Display size is 0!
: Invalid argument
ERROR: ../src/main.c:128: Failed to create uinput devices: Invalid argument
ERROR: ../src/devices.c:309: UI_DEV_DESTROY failed: Inappropriate ioctl for device
```

**Comment by ls-r** [comment]
You also mentioned that the build script failed when it didn't find systemd on your computer. For that, add the `-Dservice_manager=openrc` option when using `meson build`.

That option will also tell ninja to install an openrc init script when you run `sudo ninja -C build install` later.

**Comment by dread-pirate-johnny-spaceboots** [comment]
Right on both accounts, everything seems to be working now. Thank you sir.
