### ISSUE TITLE
iptsd Crashes on Surface Laptop Studio

### ISSUE THREAD

**Issue by samkumar** [linux-surface/iptsd#60]
When I run `iptsd`, it runs for about 5 seconds, and then crashes with the following output:
```
$ sudo iptsd
ERROR: ../src/control.c:51: Failed to send feedback: No such device
ERROR: ../src/control.c:74: Failed to flush buffers: No such device
ERROR: ../src/main.c:106: Failed to start IPTS: No such device
```
Before doing this, I inserted the `ipts` and `ithc` kernel modules, and checked that the `/dev/ipts` directory exists.

When I inserted the `ipts` and `ithc` kernel modules, the following was printed in `dmesg`:
```
[  774.501020] ipts: loading out-of-tree module taints kernel.
[  774.501096] ipts: module verification failed: signature and/or required key missing - tainting kernel
[ 1637.793985] ithc 0000:00:10.6: enabling device (0000 -> 0002)
[ 1638.017649] ithc 0000:00:10.6: config: e0000002 00000000 001fc0ff 00000010 00000014 43495424 0ce32ce8 0c1b045e 00000001 16b41b87 d9fe587a 00000000 e80f3fd4 00040302 51427d4a b7f9b403
[ 1638.018449] ithc 0000:00:10.6: registered device ithc
[ 1638.018507] input: Intel Touch Host Controller as /devices/pci0000:00/0000:00:10.6/input/input33
```
All of this looks normal to me. Nothing additional was printed out when I attempted to run `iptsd`.

Can someone please provide guidance on what this error means and how I might go about debugging it? It seems necessary to fix this in order to make the touchscreen work.

**Comment by samkumar** [comment]
The feature matrix indicates that the Surface Laptop Studio touchscreen is supported, so I hope that this is a minor mistake/oversight in configuration on my part rather than something that will require significant development.

**Comment by qzed** [comment]
As far as I know, you still need the forked IPTSd (https://github.com/quo/iptsd) for ITHC.

**Comment by samkumar** [comment]
Thanks @qzed. That worked for me.

In case others are trying to set this up, it's also worth noting that I had to change `/etc/ipts.conf` to enter the correct `Width` and `Height`. I also had to add `intremap=nosid` to the kernel command line. More details can be found https://github.com/linux-surface/linux-surface/issues/752 and https://github.com/quo/ithc-linux/issues/5.
