### ISSUE TITLE
SP4 (1B96:006A) has been tested

### ISSUE THREAD

**Issue by kitakar5525** [linux-surface/iptsd#8]
Thanks to everyone for their work, iptsd is usable now on SB1. So, I tried also on (a little bit broken) SP4, which has device `1B96:006A`, I can confirm that current config file (https://github.com/linux-surface/iptsd/blob/6d2b7a3dc82ee1d2ae9afdbb0a7df06cda0e7eb9/config/surface-pro4.conf) works for both finger and stylus just as it is.

By the way, I saw device `1B96:0021` is also used on some SP4 before (e.g. in this issue: https://github.com/linux-surface/linux-surface/issues/48#issuecomment-575848573). I'm not sure about this one.

**Comment by StollD** [comment]
Thank you for testing! I added a new config for the other SP4 device ID (called them SP4-A and SP4-B for the lack of a better name), and updated the readme to mention that the A variant has been tested.

**Comment by kitakar5525** [comment]
Thanks! Looks good to me. Closing this issue.
