### ISSUE TITLE
Touch and stylus not working on SP7

### ISSUE THREAD

**Issue by Lezurex** [linux-surface/iptsd#81]
Hello,
I got quo's version to work and actually used it in school without any major issues. I then found that quo's version got merged. I then uninstalled the old build and reinstalled the latest Arch package from GitHub Actions. However, I just can't get it to work anymore.

iptsd seems to start without any problems:
```
● iptsd@-dev-hidraw1.service - Intel Precise Touch & Stylus Daemon
     Loaded: loaded (/usr/lib/systemd/system/iptsd@.service; static)
     Active: active (running) since Sun 2022-09-25 23:23:30 CEST; 6min ago
       Docs: https://github.com/linux-surface/iptsd
   Main PID: 3479 (iptsd)
      Tasks: 1 (limit: 18681)
     Memory: 400.0K
        CPU: 5ms
     CGroup: /system.slice/system-iptsd.slice/iptsd@-dev-hidraw1.service
             └─3479 /usr/bin/iptsd /dev/hidraw1

Sep 25 23:23:30 lenny-surfacepro7 systemd[1]: Started Intel Precise Touch & Stylus Daemon.
Sep 25 23:23:30 lenny-surfacepro7 iptsd[3479]: [23:23:30.059] [info] Connected to device 045E:099F
```
dmesg also seems to be fine:
```
[  285.651286] input: IPTS Touch as /devices/virtual/input/input72
[  285.651481] input: IPTS Stylus as /devices/virtual/input/input73
```

Neither touch nor the stylus are working. I only noticed that touch works for a really short time after startup, but I couldn't find any logs indicating an issue.

I use a Surface Pro 7 with linux-surface 5.19.10. ithc and ipts modules are both loaded and also don't report any issues in dmesg.

**Comment by NP-chaonay** [comment]
> ithc and ipts modules 

ithc doesnt need if device is not at least at SP7+

ipts still need if device is not using driver from ithc, so SP7 still making use of ipts

however unncessary modprobe of ithc should not make thing worse btw

**Comment by Lezurex** [comment]
@NP-chaonay I tried again with blacklisted ithc, but the issue persists.

I just noticed the touchscreen is recognized as an unknown device. Could this have anything to do with the issue?
```
[    3.884924] hid-multitouch 0000:045E:099F.0002: input,hidraw1: <UNKNOWN> HID v0.00 Device [IPTS 045E:099F] on
```

**Comment by NP-chaonay** [comment]
> @NP-chaonay I tried again with blacklisted ithc, but the issue persists.
> 
> I just noticed the touchscreen is recognized as an unknown device. Could this have anything to do with the issue?
> 
> ```
> [    3.884924] hid-multitouch 0000:045E:099F.0002: input,hidraw1: <UNKNOWN> HID v0.00 Device [IPTS 045E:099F] on
> ```

yeah as I have said

in both ithc loaded and unloaded(including blacklisted), there should not affected the problem, so in either cases, it neither solve or worsen the problem

Anyway the recently given dmesg is interesting point, let wait for who expertise this to solve

**Comment by Lezurex** [comment]
I finally found out my problem. I was still using the ipts module, which came with the stable linux-surface kernel. Then I installed the up-to-date one, and now it works flawlessly.

Anyway, thanks a lot for your efforts. I'll close this now.
