### ISSUE TITLE
Unable to install latest IPTSD Debian Artifact on Ubuntu 20.04 for SP7+

### ISSUE THREAD

**Issue by joeyjyyang** [linux-surface/iptsd#84]
I have a SP7+ and I have been following the wiki installation instructions in: https://github.com/linux-surface/linux-surface/wiki/Installation-and-Setup. From these instructions, I have successfully:
1. Installed Ubuntu 20.04.5 Desktop from: https://releases.ubuntu.com/focal/.
2. Installed `linux-surface` kernel. Running `uname -r` outputs `5.19.8-surface`.
3. Installed `ithc`.

At this point, everything that is expected to work (from: https://github.com/linux-surface/linux-surface/wiki/Supported-Devices-and-Features) is working, except for the pen.

To get the pen working, as per the instructions, the first thing I tried was installing the latest `iptsd` `debian-latest` artifact from: https://github.com/linux-surface/iptsd/actions/runs/2998417842. However, when I try running `sudo apt install ./iptsd_0.5.1-1_amd64.deb` to install the debian, I get:

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'iptsd' instead of './iptsd_0.5.1-1_amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help resolve the situation:

The following packages have unmet dependencies:
 iptsd : Depends: libsdl2-2.0-0 (>= 2.0.12) but 2.0.10+dfsg1-3 is to be installed
E: Unable to correct problems, you have held broken packages.
```
Based on this and looking online, it seems that `libsdl2-2.0-0` only released up to version `2.0.10+dfsg1-3` for Ubuntu 20.04 (Focal), while `iptsd` requires version `2.0.12` and above.

If possible, what would be the best way to get around this? I have manually tried installing later releases of `libsdl2-2.0-0` from: https://launchpad.net/ubuntu/+source/libsdl2, but failed due to unmet dependencies.

**Comment by StollD** [comment]
We dont depend on a particular version of SDL (if you dont need the debug tools its not a dependency at all). So you could try building iptsd yourself (if you want a package check out `.github/scripts/pkg-debian.sh`).

For time and "logistical" reasons I am currently focusing only on the latest LTS versions in the Debian ecosystem (22.04 and bullseye). Managing dependencies becomes somewhat annoying when you try to build the same code on very new distros like Arch and older distros like 20.04.

**Comment by joeyjyyang** [comment]
Unfortunately i'm unable to build `iptsd` from source; running `meson build` gives me:
```
meson.build:1:0: ERROR: Meson version is 0.53.2 but project requires >=0.58.0
```

It appears to be another dependency issue coming from my older distro (Ubuntu 20.04).

Is there an older commit (or corresponding Github action artificat) that was built on Ubuntu 20.04? It does seem like some users were able to built `iptsd` on their Ubuntu 20.04 tablets in the past, so I assume they used a version of the package that targeted Ubuntu 20.04 at the time.

**Comment by joeyjyyang** [comment]
I made some progress.

I did a `git checkout 87698d6` to revert to the commit corresponding to the release of `v0.4`. I'm not sure if this contains the experimental support for the pen, but I was able to build and install `iptsd` from this commit with:
```
meson build
ninja -C build
sudo ninja -C build install
# rebooted the SP7+ at this point.
```

After this, I re-compiled `intel-precise-touch` with (I assumed that I didn't need to apply the kernel patch here, but please let me know if I should):
```
make 
sudo insmod src/ipts.ko
```

I then paired the pen to the SP7+ through `sudo bluetoothctl`; however, the `iptsd` daemon fails with:
```
● iptsd.service - Intel Precise Touch & Stylus Daemon
     Loaded: loaded (/lib/systemd/system/iptsd.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2022-09-30 12:57:33 EDT; 1s ago
       Docs: https://github.com/linux-surface/iptsd
    Process: 2549 ExecStart=/usr/local/bin/iptsd (code=exited, status=254)
   Main PID: 2549 (code=exited, status=254)

Sep 30 12:57:33 cpr-opg02-tablet systemd[1]: Started Intel Precise Touch & Stylus Daemon.
Sep 30 12:57:33 cpr-opg02-tablet iptsd[2549]: ERROR: ../src/control.c:139: Failed to open /dev/ipts/0: No such file or directory
Sep 30 12:57:33 cpr-opg02-tablet iptsd[2549]: ERROR: ../src/main.c:106: Failed to start IPTS: No such file or directory
Sep 30 12:57:33 cpr-opg02-tablet systemd[1]: iptsd.service: Main process exited, code=exited, status=254/n/a
Sep 30 12:57:33 cpr-opg02-tablet systemd[1]: iptsd.service: Failed with result 'exit-code'.
```

It seems that the pen is not appearing as the expected `/dev/ipts/0` device after bluetooth pairing with `sudo bluetoothctl`. Is this an issue with the way I paired the pen? Or did I do something wrong when re-compiling `intel-precise-touch` perhaps?

**Comment by StollD** [comment]
For ITHC and DFT pen support you need to build from master, it was not released yet.

I think you can update meson through pip, but I am not sure how well that works.

You could also try to simply extract the binaries from the 22.04 / bullseye package. Maybe it just works (a lot of iptsd is built statically on debian / ubuntu, so the chances are high).

**Comment by NP-chaonay** [comment]
@joeyjyyang 

1) /dev/ipts/0 is just device file of Intel Precise Touch and Stylus, which used for control and get data of touch+stylus
2) ```Is this an issue with the way I paired the pen?```, this not yet have thing to do with the Bluetooth stuff, your Bluetooth functionality of pen (that not tied with high required of that intel device) is not depends on that intel device, whether intel is work or not; so that BT functions should work or not work regardlesss of that Intel  device/driver
3) ```Or did I do something wrong when re-compiling intel-precise-touch perhaps?``` You recompiled ipts kernel driver, however SP7+ does not use that driver, see 4)

4) you have to check if single touch if it work or not, if it work then ithc driver go fine, if ithc work then go to 5)
5) go make the multitouch+pen work, you're required userspace daemon named ```iptsd``` (not same as ipts (without d) kernel driver) so you have to recompiled iptsd from source of Github or get prebuilt pkg from Github

**Comment by NP-chaonay** [comment]
yeah and as Dorian Stoll have said about how to install latest version, because that version have better improvement

**Comment by alirezadigi** [comment]
sorry dear @joeyjyyang 
can you please help?
what steps did you do?

**Comment by joeyjyyang** [comment]
@alirezadigi Unfortunately I wasn't able to get it working. Because of the tight deadline for my project, I instead purchased a cheap capacitive pen on Amazon, and used it instead.

**Comment by LazuliKao** [comment]
I am not professional, but only met the same problem of dependencies.
I tried many ways to search and then find this issue, but still difficult for me to solve any libsdl2-2.0-0.
by accident, I download the 'deb' file from the releases page, and use `dpkg -i --force-depends xxx.deb`, it is fun to just skip the dependency check but actually it seems to work fine for me (with only 2.0.10+dfsg1-3)
so I share this silly solution of '--force-depends' , hope it can help you.
(((
