### ISSUE TITLE
iptsd does not run on SLS

### ISSUE THREAD

**Issue by gerassimosbarlas** [linux-surface/iptsd#85]
I have followed the installation instructions and even compiled the kernel after applying the patches, to no avail.
This is what I get after booting up:
$ service iptsd status
× iptsd.service - Intel Precise Touch & Stylus Daemon
     Loaded: loaded (/lib/systemd/system/iptsd.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2022-09-30 11:47:26 +04; 35min ago
       Docs: https://github.com/linux-surface/iptsd
    Process: 3861 ExecStart=/usr/bin/iptsd (code=exited, status=237/KEYRING)
   Main PID: 3861 (code=exited, status=237/KEYRING)
        CPU: 2ms

Sep 30 11:47:21 axerontas systemd[1]: Started Intel Precise Touch & Stylus Daemon.
Sep 30 11:47:26 axerontas iptsd[3861]: ERROR: ../src/control.c:51: Failed to send feedback: No such device
Sep 30 11:47:26 axerontas iptsd[3861]: ERROR: ../src/control.c:74: Failed to flush buffers: No such device
Sep 30 11:47:26 axerontas iptsd[3861]: ERROR: ../src/main.c:106: Failed to start IPTS: No such device
Sep 30 11:47:26 axerontas systemd[1]: iptsd.service: Main process exited, code=exited, status=237/KEYRING
Sep 30 11:47:26 axerontas systemd[1]: iptsd.service: Failed with result 'exit-code'.

Modules ithc and ipts are loaded and the /dev/ipts directory exists. 

Output of dmesg:
$ sudo dmesg | grep -Ei 'ithc|linux version|dmi:|class 0x0901'
[    0.000000] Linux version 5.19.11-linux-surface (gbarlas@axerontas) (gcc (Ubuntu 9.4.0-5ubuntu1) 9.4.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #1 SMP PREEMPT_DYNAMIC Wed Sep 28 11:13:53 +04 2022
[    0.000000] DMI: Microsoft Corporation Surface Laptop Studio/Surface Laptop Studio, BIOS 18.101.141 12/15/2021
[    0.483933] pci 0000:00:10.6: [8086:a0d0] type 00 class 0x090100
[    3.694659] ithc: loading out-of-tree module taints kernel.
[    3.694683] ithc: module verification failed: signature and/or required key missing - tainting kernel
[    3.705341] ithc 0000:00:10.6: enabling device (0000 -> 0002)
[    3.930514] ithc 0000:00:10.6: config: e0000002 00000000 001fc0ff 00000010 00000014 43495424 0de319e8 0c1b045e 00000001 56904992 d47d5056 00000000 dee30582 00040302 d9653800 40ebff60
[    3.930846] ithc 0000:00:10.6: registered device ithc
[    4.962839] ithc 0000:00:10.6: ithc_probe: hid_add_device failed with -110
[    4.962845] ithc: probe of 0000:00:10.6 failed with error -110
[ 1214.426211]  industrialio snd_hda_codec snd_hda_core snd_hwdep hid_sensor_hub hid_multitouch joydev input_leds iwlmvm intel_rapl_msr intel_rapl_common uvcvideo overlay videobuf2_vmalloc intel_tcc_cooling snd_pcm snd_seq_midi mac80211 videobuf2_memops x86_pkg_temp_thermal hid_generic intel_powerclamp snd_seq_midi_event videobuf2_v4l2 btusb videobuf2_common btrtl coretemp nvidia_drm(POE) libarc4 nvidia_modeset(POE) btbcm snd_rawmidi pmt_telemetry binfmt_misc surface_platform_profile surface_hid btintel platform_profile surface_hid_core surface_aggregator_tabletsw surface_battery surface_charger pmt_class gpio_keys surface_gpe mei_pxp btmtk videodev snd_seq mei_hdcp iwlwifi snd_seq_device nls_iso8859_1 mc kvm_intel bluetooth snd_timer cmdlinepart kvm nvidia(POE) ecdh_generic spi_nor ecc mei_me snd ithc(OE) intel_cstate cfg80211 soundcore mtd mei 8250_dw hid intel_vsec igen6_edac surfacepro3_button mac_hid soc_button_array surface_aggregator_registry acpi_tad acpi_pad sch_fq_codel

I have tried setting intremap=nosid as a kernel parameter. Still does not work.
Any help will be appreciated.

**Comment by StollD** [comment]
You need to build iptsd from source. The iptsd you are running is the build from the package repository, which does not support ITHC based devices.

**Comment by gerassimosbarlas** [comment]
Solved: after I installed the linux-surface kernel I installed he iptsd module. It is not working. Thank you all.

**Comment by buttergrillcorn** [comment]
> Solved: after I installed the linux-surface kernel I installed he iptsd module. It is now working. Thank you all for your efforts. 

Hey, sorry to bother. I'm currently using and learning NixOS and came across this problem. I'm struggling to find a solution, can you tell me what you did to solve this? Thank you!
