### ISSUE TITLE
dev-ipts.device: Job dev-ipts.device/start timed out

### ISSUE THREAD

**Issue by tihoulas** [linux-surface/iptsd#9]
Hi,

I built and installed kernel 5.6.6 using the uapi patches, then buit and tested (manually launching) iptsd.
It worked perfectly, so I figured I would install the daemon using systemd.
However, the service won't start before a few minutes after boot (and then it works).
journalctl provides the following information :

`dev-ipts.device: Job dev-ipts.device/start timed out`

As the iptsd.service is waiting for dev-ipts.device to start, it won't start until this timeout.
/dev/iptsd is present however.

**Comment by StollD** [comment]
Could you try to put this into a file `/etc/udev/rules.d/50-iptsd.rules`?

```
 KERNEL=="ipts", TAG+="systemd"
```

**Comment by tihoulas** [comment]
That solved it, thanks.
