### ISSUE TITLE
iptsd-find-hidraw does not work if dmesg is clear

### ISSUE THREAD

**Issue by NP-chaonay** [linux-surface/iptsd#96]
is there any alternative solution

dmesg -c can possible by many power user especially when that user have to debug seomthing about driver/kernel.

I am volunteer of iptsd/ithc/linux-surface, so I cannot avoid dmesg -C

**Comment by NP-chaonay** [comment]
maybe we want to take a look at this

`cat /sys/class/hidraw/hidraw*/device/uevent`

this is proper way and more stable way (idk if hidraw stuff changing dmesg output or not)

**Comment by StollD** [comment]
That seems like a good idea. I also dont think the sysfs files are locked down on debian / arch, so you wouldnt need root to run the script.

Could you check if this command returns the correct hidraw device for you?

```bash
grep -E "IPTS|Intel Touch Host Controller" /sys/class/hidraw/*/device/uevent | tail -n1 | grep -Eo 'hidraw[0-9]+'
```

**Comment by NP-chaonay** [comment]
> ```shell
> grep -E "IPTS|Intel Touch Host Controller" /sys/class/hidraw/*/device/uevent | tail -n1 | grep -Eo 'hidraw[0-9]+'
> ```

yeah correctly , without using of root permission

it output hidraw0 (iptsd-find-hidraw output /dev/hidraw0)
