### ISSUE TITLE
Possible race condition suspicion that cause new instance of iptsd failed instantly 

### ISSUE THREAD

**Issue by NP-chaonay** [linux-surface/iptsd#97]
https://github.com/quo/ithc-linux/issues/20#issuecomment-1324708779

This is cause why I created this issue
Brief: StollD wonder if race condition cause the problem that: when ithc is restarted, why the new instance of iptsd (which instanced when ithc is inserted to kernel and found the ithc device) is failed (when ithc restarted, it seem that old iptsd is exited itself normally) , but ithc is working but seem have something locking thus making touch don't work.

**Comment by StollD** [comment]
Please add the following line to the bottom of the iptsd service file (`/usr/lib/systemd/system/iptsd@.service`):

```
LimitCORE=infinity
```

Then reboot, and reproduce the crash by reloading the module when iptsd is active. After it has crashed, `coredumpctl list iptsd` should show an entry. Export it by running `coredumpctl dump iptsd > iptsd.core` and upload the `iptsd.core` file.

**Comment by StollD** [comment]
Dammit, I forgot one critical step: You need to build and install iptsd with debug symbols. Otherwise the coredump wont be compatible with the debug build on my machine.

```
apt uninstall iptsd
meson build -Dbuildtype=debugoptimized
ninja -C build
sudo meson install -C build --skip-subprojects
```

**Comment by StollD** [comment]
Alternatively you could try the packages that are building right now. These should hopefully make the packaged binaries compatible with my local builds.

**Comment by NP-chaonay** [comment]
@StollD it is possible that I using older version somewhere in commit Nov?

**Comment by NP-chaonay** [comment]
cannot reproduce at this moment and I give up

so If I found symptom then I will reopen
